
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong
          image: kong:latest
          ports:
            - containerPort: 8000  # HTTP proxy
            - containerPort: 8443  # HTTPS proxy
            - containerPort: 8001  # Admin API (HTTP)
            - containerPort: 8002  # Admin GUI
            - containerPort: 8444  # Admin API (HTTPS)
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "kong-database"
            - name: KONG_PG_USER
              value: "kong"
            - name: KONG_PG_PASSWORD
              value: "kongpass"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
            - name: KONG_ADMIN_GUI_URL
              value: "http://localhost:8002"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
spec:
  type: LoadBalancer
  ports:
    - name: proxy
      port: 8000
      targetPort: 8000
    - name: proxy-ssl
      port: 8443
      targetPort: 8443
  selector:
    app: kong-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
spec:
  type: LoadBalancer
  ports:
    - name: admin
      port: 8001
      targetPort: 8001
    - name: admin-gui
      port: 8002
      targetPort: 8002
    - name: admin-ssl
      port: 8444
      targetPort: 8444
  selector:
    app: kong-gateway
