
apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
spec:
  template:
    spec:
      containers:
      - name: kong
        image: kong:latest
        command: ["kong", "migrations", "bootstrap"]
        env:
          - name: KONG_DATABASE
            value: "postgres"
          - name: KONG_PG_HOST
            value: "kong-database"
          - name: KONG_PG_PASSWORD
            value: "kongpass"
      restartPolicy: OnFailure
  backoffLimit: 3
