
apiVersion: v1
kind: Service
metadata:
  name: kong-database
  labels:
    app: kong
spec:
  ports:
    - port: 5432
  selector:
    app: kong-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  labels:
    app: kong-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "kong"
          - name: POSTGRES_DB
            value: "kong"
          - name: POSTGRES_PASSWORD
            value: "kongpass"
